### ISSUE TITLE
"Reset" doesn't add Muffins

### ISSUE THREAD

**Issue by baxil** [blackhole12/PonyClicker#11] opened 2015-05-14 22:19 UTC
Using the Reset function brought up a notification saying I'd earned a large number of Muffins, but the Muffins display in the Menu did not change and the value exported in the save file did not change.

**Comment by blackhole12** [comment] 2015-05-14 22:22
Intended behavior because muffins are broken. The notification should be removed, though.

**Comment by blackhole12** [comment] 2015-05-14 22:26
Fixed in master, pending verification and merge to production.

**Comment by baxil** [comment] 2015-05-14 22:47
Then what's the point of resetting?  Without a muffin bonus, there's no bonus for doing so at all; it's equivalent to a wipe except that you keep achievements.

Worse, Reset also resets your "Pony Clicks" so it makes it harder to get the click-based achievements.

**Comment by blackhole12** [comment] 2015-05-14 23:13
ATM there is no point in resetting, this is a temporary fix to keep it from breaking the entire game. Resetting is supposed to involve some sort of prestige mechanism, but I need one that doesn't nuke the entire game. If I can't think of one i will disable resetting entirely.

**Comment by blackhole12** [comment] 2015-05-15 00:51
Resetting has been completely removed until I figure out a better way to do it. If you have a suggestion for a prestige system, please file an "enhancement" issue describing it.

**Closed by blackhole12** 2015-05-15 00:51 UTC
Labels: wontfix
