### ISSUE TITLE
Amusing lower limit (may not be fixable).

### ISSUE THREAD

**Issue by TricksterWolf** [blackhole12/PonyClicker#42] opened 2015-05-16 03:58 UTC
Predicted S/s increase is reduced to a specific number when it underflows.  This makes all buildings look like they will generate the same amount.  In my game, everything but four categories (first two and last two) claim to generate another 9.007E15 S/s for your next purchase.

It would be much better to print "practically nothing" if the next increase in S/s for a purchase is less than 1/(10E9) the current S/s.  This would remove it long before reaching the cutoff (the cutoff lies about a factor of a billion below current S/s, so a factor of a million would do it; getting close to the cutoff appears to cause minor rounding errors so it'd be best to buffer against it).

**Comment by TricksterWolf** [comment] 2015-05-16 04:01
Update: it also affects the "you pay" metric, but this should be obvious.

**Comment by blackhole12** [comment] 2015-05-16 04:10
I'd prefer to push against the cutoff a lot harder, because having rounding errors is better than reducing it to "practically nothing", which is going to confuse the players no matter what. In addition, the cutoff here sounds abnormally large. Javascript should be using IEEE 64-bit doubles, which have a 52-bit mantissa. Given 4 bits of information left, that would be a factor of 2^48 or 281474976710656, which is 281 trillion. If buildings have underflowed so much they have been reduced to generating the same amount, javascript is doing bullshit again and I want to know what it is. 4 bits is enough to store 8 discrete points, which should be barely enough to differentiate lower buildings.

What could also be happening is that one of the buildings started underflowing a long time ago, and once another building has caught up, they're actually underflowing by an enormous amount already.

I'm going to guess that this could largely be fixed by looking for anything generating lower than 2^-48 times the SPS, because the smaller buildings will get set to "almost nothing" long before the next building up would start underflowing.

Also, how about we replace it with "this buliding is generating an **insignificant** number of cookies"? This seems to convey the idea better.

**Comment by Jesin** [comment] 2015-05-16 04:34
We could try this:
https://en.wikipedia.org/wiki/Quadruple-precision_floating-point_format#Double-double_arithmetic

**Comment by blackhole12** [comment] 2015-05-16 05:08
I can't replicate this issue. For me, when the SPS gets too high, it just displays "0" instead of a lower limit. Can you provide a save file that demonstrates this?

**Comment by TricksterWolf** [comment] 2015-05-16 15:44
Note that Recital through Rave all have the same predicted S/s increase
(10.436 quadrillion as I recall):

{"upgrades":[1,7,2,8,9,10,11,12,13,14,15,16,17,18,19,20,21,4,3,5,6],"upgradeHash":{"1":1,"2":2,"3":3,"4":4,"5":5,"6":6,"7":7,"8":8,"9":9,"10":10,"11":11,"12":12,"13":13,"14":14,"15":15,"16":16,"17":17,"18":18,"19":19,"20":20,"21":21},"smiles":8.041241894213592e+31,"totalsmiles":4.8446325708196834e+32,"SPC":1.0343445181393678e+27,"SPS":1.034344518139368e+28,"shiftDown":false,"totalTime":17604000,"clicks":17604,"achievements":{"1":0,"2":0,"3":1,"4":2,"5":3,"6":4,"10":1,"11":2,"12":3,"13":4,"14":5,"15":6,"16":7,"17":8,"18":9,"19":10,"20":1,"21":2,"22":3,"23":4,"24":5,"25":1,"26":2,"27":3,"28":4,"29":5,"30":1,"31":2,"32":3,"33":4,"34":5,"35":1,"36":2,"37":3,"38":4,"39":5,"40":1,"41":2,"42":3,"43":4,"44":5,"45":1,"46":2,"47":3,"48":4,"50":1,"51":2,"52":3,"55":1,"56":2,"57":3,"60":1,"61":2,"62":3,"65":1,"66":2,"67":3,"68":4,"69":5,"200":1,"201":1,"202":1,"203":1,"204":1,"205":1},"achievementcount":65,"muffins":352,"achievement_muffins":189,"store":[24,255,310,275,240,210,200,150,130,110,100,82,0],"ponyList":[0,37,9,49,52,40,57,1,38,29,51,6,7,26,47,21,22,28,10,55,56,35,20,5,53,11,34,16,41,45,50,48,32,12,23,24,31,30,17,46,25,13,3,8,27,54,14,15,18,33,2,4,42,19,39,43,36,44],"version":3,"settings":{"useCanvas":true,"optimizeFocus":false,"closingWarn":false},"delta":32.99699997296557}

On Sat, May 16, 2015 at 1:08 AM, Erik McClure <notifications@github.com>
wrote:

> I can't replicate this issue. For me, when the SPS gets too high, it just
> displays "0" instead of a lower limit. Can you provide a save file that
> demonstrates this?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/blackhole12/PonyClicker/issues/42#issuecomment-102571965>
> .
>



-- 
Trick Question

**Comment by blackhole12** [comment] 2015-05-17 06:46
As an amusing note, Cookie Clicker suffers from this problem as well, and the precision cutoff appears to be in roughly the same place.

![image](https://cloud.githubusercontent.com/assets/3387013/7669382/be0a8d88-fc25-11e4-89bd-a181bf82a258.png)

**Comment by TricksterWolf** [comment] 2015-05-17 19:51
That's pretty hilarious.  I haven't played CC in years, myself.

I'll do that mockup later today.

On Sun, May 17, 2015 at 2:46 AM, Erik McClure <notifications@github.com>
wrote:

> As an amusing note, Cookie Clicker suffers from this problem as well, and
> the precision cutoff appears to be in roughly the same place.
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/3387013/7669382/be0a8d88-fc25-11e4-89bd-a181bf82a258.png>
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/blackhole12/PonyClicker/issues/42#issuecomment-102756082>
> .
>



-- 
Trick Question

**Comment by blackhole12** [comment] 2015-05-21 08:11
I was able to replicate this problem on my own and confirmed that we're looking at a lowerbound of almost exactly 2^51, which is what we expect from a 64-bit double with a 52 bit mantissa. However, it is also possible to see the precision issue much higher up. I was able to spot SPS increases going [i]down[/i] after buying a building due to precision issues, and that was only counted as too small when compared to a value of 2^47, which is a significantly larger dead zone. For right now I'm going to use 2^47 to mark the lower bound, but it may need tweaking in the future.

**Closed** 2015-05-21 08:16 UTC
Labels: enhancement
