### ISSUE TITLE
The SPC shown in the menu and the SPC pop up don't always match

### ISSUE THREAD

**Issue by Two-Tone** [blackhole12/PonyClicker#14] opened 2015-05-14 22:57 UTC
[Screenshot showing the issue](http://i.imgur.com/6RRIOSx.png)

**Comment by blackhole12** [comment] 2015-05-14 23:15
Duplicate of this issue: https://github.com/blackhole12/PonyClicker/issues/3

**Closed** 2015-05-14 23:15 UTC
Labels: duplicate
